#ifndef GENERATINGSET_H
#include "puzdef.h"
#include <vector>
using namespace std;
/*
 *   A Schreier-Sims stabilizer chain for the group generated by the moves.
 *   Only sets whose pieces are all distinct and have no orientation
 *   wildcards take part.  Other sets only get basic checks: within each
 *   orbit of locations under the moves, the piece counts must match the
 *   solved position, and the orientation sum must match modulo what the
 *   moves can change it by.  Passing is a necessary (not sufficient)
 *   condition for a position to be solvable.
 */
struct generatingset {
  generatingset(const puzdef &pd);
  const puzdef &pd;
  allocsetval e;
  vector<vector<allocsetval>> sgs, sgsi, tk;
  vector<char> included; // per set
  int lastincluded;      // index of last included set, or -1 if none
  // for excluded sets: orbit of each location, solved piece counts per
  // (orbit, piece), and per orbit the modulus of the orientation sum
  // (1 if unconstrained) and the solved orientation sum
  vector<vector<int>> orbit, solvedcnt, orimod, solvedori;
  void initbasiccheck(int i);
  bool basiccheck(const setval p) const;
  static bool eligible(const setdef &sd) { return sd.uniq && !sd.wildo; }
  bool resolve(const setval p_);
  void showsizes() const;
  bool solvable(const setval p); // p relative to the solved position
  void knutha(int k1, int k2, const setval &p);
  void knuthb(int k1, int k2, const setval &p);
};
#define GENERATINGSET_H
#endif
