#ifndef SUBGROUP_H
#include "puzdef.h"
extern const char *subgroupmovelist;
// Mutates pd.solved (and setdef properties) to encode "solved within the
// subgroup generated by the given comma-separated move list".
extern void runsubgroup(puzdef &pd, const char *moves);
// Convenience overload that reads from the global subgroupmovelist.
extern void runsubgroup(puzdef &pd);
#define SUBGROUP_H
#endif
